### ISSUE TITLE
Not all entries downloaded

### ISSUE THREAD

**Issue by viertelb** [blackbunt/dump-discogs-collection-2-csv#2]
The Excel was missing several items of my collection. 

(I might debug this myself one day.)

**Comment by blackbunt** [comment]
Could you provide the discogs release id s for the missing ones

**Comment by viertelb** [comment]
My collection is small (https://www.discogs.com/user/bomben/collection) this still might be the reason. If I sort for newest, which also was the way the Excel was sorted originally, it seems that it downloaded 125 old entries and then skipped all the others, which where newer ones. .

Not included in the download are those and more: 

- https://www.discogs.com/Me-Avalon-EP/release/10517165
- https://www.discogs.com/Ansome-Penny-Pound-EP-/release/6021043
- https://www.discogs.com/Avion-9-Leytonstone-Stefan-Rein-schelf-Untitled/release/7960905
- https://www.discogs.com/Emmanuel-Installations/release/7868278

**Comment by blackbunt** [comment]
Sorry for the late reply. I was able to reproduce the error, i think the problem is somewhere in the processing of the data. The API requests are working. Maybe there is a problem with the regex. I'll look into it, but i don't have much time right now.

**Comment by viertelb** [comment]
Funny, I also checked it yesterday evening. I get 179 items from the API, but some of them are empty (row is empty), which results in lesser items that are written to the file.

**Comment by viertelb** [comment]
This will be solved by https://github.com/blackbunt/dump-discogs-collection-2-csv/pull/3#issue-1007047838.
